insert into countries (name, full_name, internationalname, code2) values ('United States', 'Clari Stilliard', 'in quam', 'lnc708');
insert into countries (name, full_name, internationalname, code2) values ('Bulgaria', 'Vince Samett', 'turpis sed ante', 'eyt004');
insert into countries (name, full_name, internationalname, code2) values ('China', 'Abbi Pallant', 'lobortis convallis', 'mff574');
insert into countries (name, full_name, internationalname, code2) values ('Vietnam', 'Conney Yakhin', 'nulla', 'jie242');
insert into countries (name, full_name, internationalname, code2) values ('Czech Republic', 'Maddy Joselovitch', 'sapien non', 'xrn576');
insert into countries (name, full_name, internationalname, code2) values ('Poland', 'Al Clapson', 'volutpat', 'bjb448');
insert into countries (name, full_name, internationalname, code2) values ('Canada', 'Cherri Endle', 'et ultrices posuere', 'uxz434');
insert into countries (name, full_name, internationalname, code2) values ('Ukraine', 'Jessie Seaborne', 'dui luctus rutrum', 'waw167');
insert into countries (name, full_name, internationalname, code2) values ('Tanzania', 'Allyce Thonason', 'nulla pede ullamcorper', 'acf568');
insert into countries (name, full_name, internationalname, code2) values ('Indonesia', 'Leroi Brodest', 'venenatis', 'nse472');
insert into countries (name, full_name, internationalname, code2) values ('Nigeria', 'Pinchas Trewman', 'sed vestibulum sit', 'bdf089');
insert into countries (name, full_name, internationalname, code2) values ('Japan', 'Emogene Robey', 'a', 'lid173');
insert into countries (name, full_name, internationalname, code2) values ('Costa Rica', 'Delphine Swinn', 'est', 'ptd094');
insert into countries (name, full_name, internationalname, code2) values ('Russia', 'Morgen Von Der Empten', 'enim', 'bxx451');
insert into countries (name, full_name, internationalname, code2) values ('Philippines', 'Dag Willan', 'lobortis', 'mxg866');
insert into countries (name, full_name, internationalname, code2) values ('Yemen', 'Clarke Bank', 'nulla ac', 'xzv644');
insert into countries (name, full_name, internationalname, code2) values ('Ecuador', 'Munmro Calveley', 'eget semper', 'rpj497');
insert into countries (name, full_name, internationalname, code2) values ('Chile', 'Claudio Dawdry', 'nec molestie sed', 'hbh583');
insert into countries (name, full_name, internationalname, code2) values ('Finland', 'Ramon Jonson', 'vestibulum ac', 'srg858');
insert into countries (name, full_name, internationalname, code2) values ('Togo', 'Ailbert Wetherhead', 'consequat', 'tdn179');
insert into countries (name, full_name, internationalname, code2) values ('Madagascar', 'Brit Chretien', 'mi sit amet', 'lvm588');
insert into countries (name, full_name, internationalname, code2) values ('Uzbekistan', 'Bealle Gadie', 'turpis enim blandit', 'cjv455');
insert into countries (name, full_name, internationalname, code2) values ('Thailand', 'Kirk Manville', 'justo in', 'deb916');
insert into countries (name, full_name, internationalname, code2) values ('Panama', 'Caroline Laetham', 'vestibulum eget vulputate', 'abt059');
insert into countries (name, full_name, internationalname, code2) values ('Macedonia', 'Lauren Greensitt', 'eget congue eget', 'pbo503');
insert into countries (name, full_name, internationalname, code2) values ('Qatar', 'Archibald Blues', 'potenti in eleifend', 'uki949');
insert into countries (name, full_name, internationalname, code2) values ('Egypt', 'Sheilah Dowglass', 'potenti nullam', 'fye519');
insert into countries (name, full_name, internationalname, code2) values ('Colombia', 'Fey Dyshart', 'dapibus', 'hna601');
insert into countries (name, full_name, internationalname, code2) values ('Belarus', 'Janie Macci', 'sed interdum', 'wqe637');
insert into countries (name, full_name, internationalname, code2) values ('Bosnia and Herzegovina', 'Gaelan Labuschagne', 'adipiscing molestie hendrerit', 'jpi380');
insert into countries (name, full_name, internationalname, code2) values ('Peru', 'Cate Tuttle', 'maecenas ut', 'llk852');
insert into countries (name, full_name, internationalname, code2) values ('Ivory Coast', 'Janaya Shoutt', 'nonummy', 'xuf584');
insert into countries (name, full_name, internationalname, code2) values ('Mexico', 'Aldis Salasar', 'pretium iaculis', 'jvp224');
insert into countries (name, full_name, internationalname, code2) values ('Bangladesh', 'Emalia Corain', 'vestibulum', 'zhl774');
insert into countries (name, full_name, internationalname, code2) values ('Sweden', 'Antonetta Choat', 'accumsan', 'heb819');
insert into countries (name, full_name, internationalname, code2) values ('Pakistan', 'Dasya Chern', 'sapien', 'luv312');
insert into countries (name, full_name, internationalname, code2) values ('Paraguay', 'Anthony Painswick', 'pulvinar nulla pede', 'tro395');
insert into countries (name, full_name, internationalname, code2) values ('Mongolia', 'Breanne Esslemont', 'sed', 'uwe981');
insert into countries (name, full_name, internationalname, code2) values ('Armenia', 'Karine Claydon', 'blandit', 'toy004');
insert into countries (name, full_name, internationalname, code2) values ('France', 'Brynn Penswick', 'curabitur', 'odh498');

insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Vihti', 72, 22, 'Bultman', 'eu');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Glad', 79, 39, 'Bunting', 'rutrum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Valencia', 25, 38, 'West', 'morbi');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Sumusţā as Sulţānī', 53, 28, 'Oakridge', 'morbi');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kačanik', 35, 6, 'Garrison', 'sociis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Lashma', 81, 35, 'Meadow Valley', 'congue');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Weiyanggong', 95, 34, 'Sunfield', 'nisl');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Lom Sak', 7, 6, 'Mesta', 'turpis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Zumarraga', 20, 9, 'Anzinger', 'aenean');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Akashi', 28, 5, 'Springs', 'consequat');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Huanshan', 25, 34, 'Carioca', 'vestibulum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Aricagua', 65, 28, '4th', 'aliquet');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Depok', 9, 6, 'Parkside', 'elit');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Sarykemer', 33, 33, 'Maple', 'eros');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Cachoeirinha', 83, 5, 'Pawling', 'magnis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Detupia', 3, 31, 'Chinook', 'tristique');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Moravská Nová Ves', 1, 30, 'Browning', 'potenti');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Revolucion Verde', 3, 29, 'Nova', 'consequat');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Altan-Ovoo', 2, 28, 'Anhalt', 'at');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Ghouazi', 69, 27, 'Amoth', 'pede');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Pirca', 98, 26, 'Cardinal', 'convallis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Mantalongon', 12, 25, 'Barby', 'etiam');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Oefatu', 66, 24, 'Rockefeller', 'blandit');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nancy', 41, 23, 'Cardinal', 'id');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Zhongdong', 100, 22, 'Acker', 'dignissim');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Fonte Boa', 27, 21, 'Maywood', 'id');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Gvardeysk', 94, 20, 'John Wall', 'bibendum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Farafenni', 92, 19, 'Miller', 'morbi');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Velagići', 61, 18, 'Burrows', 'justo');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nechanice', 12, 17, 'Jenna', 'scelerisque');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Zhaowanzhuang', 39, 16, 'Dryden', 'nulla');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Longwu', 57, 32, 'Farragut', 'suspendisse');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Verkhnevilyuysk', 90, 15, 'Hallows', 'habitasse');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Polo', 31, 5, 'Southridge', 'non');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kefar Yona', 17, 8, 'Clove', 'mattis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Zhigulevsk', 6, 14, 'Katie', 'nulla');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Amānzī', 85, 13, 'Hallows', 'quis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Niono', 40, 12, 'Manitowish', 'aliquam');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Xiangfu', 75, 11, 'Hanson', 'sollicitudin');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nay Pyi Taw', 69, 10, 'Brentwood', 'nulla');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kebonbencoy', 73, 34, 'Mandrake', 'posuere');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nangkasari', 80, 36, 'Onsgard', 'dictumst');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Trois-Rivières', 16, 9, 'Waubesa', 'felis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Batasan Bata', 78, 31, 'Loftsgordon', 'fermentum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Frederiksberg', 45, 26, 'Vera', 'ipsum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Chang’an', 5, 8, 'Summit', 'aliquet');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Cikabuyutan Barat', 20, 7, 'Jay', 'ac');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Río Alejandro', 96, 6, 'Fieldstone', 'vel');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Sidi Moussa', 90, 5, 'Garrison', 'vitae');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Serednye Vodyane', 59, 2, 'Anniversary', 'ligula');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Naru', 30, 1, 'Steensland', 'porttitor');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Banjar Sedang', 47, 2, 'Sommers', 'massa');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Aricapampa', 44, 3, 'Bashford', 'odio');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Perpignan', 100, 4, 'Summer Ridge', 'consequat');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Soavinandriana', 57, 39, 'Nelson', 'augue');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('João Pessoa', 23, 12, 'Tennyson', 'venenatis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Shchëkino', 75, 4, 'New Castle', 'faucibus');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Burgastai', 52, 5, 'Superior', 'justo');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Ruyigi', 40, 6, 'Pawling', 'eget');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Daxing', 45, 10, 'Helena', 'cubilia');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Wiset Chaichan', 67, 11, 'Texas', 'nulla');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kondinskoye', 26, 12, 'Prentice', 'libero');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Castainço', 39, 16, 'Di Loreto', 'nullam');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Magapit', 45, 13, 'Bowman', 'tortor');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Tilburg', 59, 14, 'Division', 'mi');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Gazli', 28, 23, 'Esker', 'magna');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Irará', 31, 15, 'Raven', 'nullam');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Chiguirip', 92, 16, 'Springview', 'consectetuer');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Tlatah', 66, 37, 'Loomis', 'mi');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Colonia Yguazú', 31, 17, 'Crescent Oaks', 'lacus');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kalianda', 66, 18, 'Vidon', 'parturient');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Būr Safājah', 42, 19, 'Dryden', 'tempus');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kalmar', 67, 20, 'Eliot', 'quam');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Phủ Thông', 87, 1, 'Forest', 'nunc');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Jianyi', 63, 34, 'Veith', 'libero');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Fresno', 86, 12, 'Pine View', 'orci');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Pokrovka', 43, 27, 'Vidon', 'fusce');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nsukka', 71, 26, 'American', 'at');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Bang Phae', 77, 22, 'Anniversary', 'nunc');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Lijia', 83, 23, 'Chinook', 'ipsum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Duishan', 43, 11, 'Springs', 'venenatis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Claye-Souilly', 93, 24, 'Wayridge', 'non');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Linmansangan', 97, 36, 'Sage', 'curae');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Ambatolampy', 81, 24, 'Moulton', 'varius');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Couço', 6, 39, 'Bowman', 'sit');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kaminoyama', 97, 25, 'Buena Vista', 'nunc');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Banquero', 81, 26, 'Division', 'suspendisse');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Stockholm', 33, 23, 'Crest Line', 'in');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Zhenziliang', 100, 27, 'Manitowish', 'id');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Luowan', 63, 28, 'Dunning', 'est');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Moryń', 23, 29, 'Lindbergh', 'quis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Novyye Cherëmushki', 18, 31, 'Bultman', 'iaculis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Desa Borogojol', 78, 32, 'Waxwing', 'integer');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Dalkey', 100, 1, 'Myrtle', 'rhoncus');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Tongyang', 15, 33, 'Mosinee', 'vestibulum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('San Antonio del Monte', 69, 15, '5th', 'sapien');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Piritiba', 1, 34, 'Blackbird', 'sed');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nobres', 97, 35, 'Kedzie', 'hac');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Parzęczew', 31, 27, 'Debs', 'magnis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Chabany', 98, 36, 'Myrtle', 'cum');
