insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-01-14 19:02:46', 71, 50, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-06-14 14:44:32', 87, 49, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-31 22:28:06', 21, 42, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-03-14 05:32:23', 99, 15, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-20 10:46:31', 7, 61, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-02 04:43:16', 67, 38, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-16 22:29:47', 85, 68, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-04-30 04:47:09', 99, 89, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-04-05 06:09:03', 97, 93, 'DECLINED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-11-27 11:55:15', 35, 24, 'BLOCKED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-02-03 01:18:16', 25, 14, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-13 00:37:43', 14, 5, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-04 07:53:45', 20, 77, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-15 20:57:20', 59, 84, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-11 06:55:24', 76, 66, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-02-10 11:33:49', 70, 24, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-30 16:45:50', 25, 36, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-01-09 08:35:39', 29, 99, 'DECLINED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-07-03 03:00:02', 18, 91, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-02-13 10:49:20', 58, 77, 'BLOCKED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-09-18 01:35:45', 60, 3, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-09-13 05:06:04', 57, 89, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-18 22:59:59', 58, 20, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-27 11:14:16', 52, 94, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-12-22 02:10:19', 76, 73, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-06-14 22:17:42', 40, 48, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-12-26 02:33:30', 56, 37, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-12 16:04:48', 96, 12, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-01-31 00:47:06', 25, 3, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-03-25 16:23:10', 68, 22, 'BLOCKED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-16 22:04:11', 71, 63, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-11-08 22:55:59', 70, 98, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-03-16 23:27:49', 14, 20, 'DECLINED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-25 08:00:02', 84, 90, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-16 10:12:55', 31, 82, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-02-02 09:42:55', 48, 18, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-04-09 18:35:38', 15, 71, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-11 18:46:17', 74, 4, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-28 19:15:41', 70, 70, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-11-01 11:43:45', 11, 6, 'BLOCKED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-07 08:38:27', 15, 43, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-03-26 01:12:16', 74, 47, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-23 01:55:02', 83, 87, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-02-05 22:30:01', 4, 40, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-01 16:58:36', 54, 9, 'DECLINED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-07-28 19:03:10', 40, 81, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-12-09 01:50:23', 17, 48, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-06-07 10:12:00', 42, 95, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-07-13 23:14:56', 19, 12, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-11-09 15:54:19', 25, 93, 'BLOCKED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-03-26 09:34:01', 75, 58, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-07-25 03:00:40', 37, 54, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-28 04:05:37', 21, 10, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-12-12 14:43:45', 48, 70, 'DECLINED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-03-30 19:15:27', 52, 79, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-04-08 11:44:56', 85, 79, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-02-12 15:56:41', 52, 50, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-09-03 14:15:37', 88, 94, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-02-19 21:28:32', 90, 3, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-02-19 14:02:21', 76, 87, 'BLOCKED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-25 22:57:11', 67, 53, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-09-27 05:06:08', 76, 6, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-29 19:18:44', 37, 21, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-19 13:31:13', 18, 87, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-09-14 12:50:34', 99, 1, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-02-02 13:57:43', 84, 36, 'DECLINED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-01-30 20:00:49', 2, 6, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-09 13:25:01', 37, 27, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-04-02 18:44:48', 13, 84, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-06-11 11:12:45', 86, 90, 'BLOCKED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-04-21 06:04:04', 13, 83, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-06-17 13:17:53', 32, 74, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-12-13 16:29:16', 21, 19, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-11 20:29:21', 25, 11, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-07 04:20:42', 80, 11, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-09-04 02:33:40', 49, 98, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-09-18 17:48:45', 11, 16, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-11-29 15:42:59', 76, 16, 'DECLINED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-09-13 08:02:12', 10, 86, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-25 08:42:37', 40, 59, 'BLOCKED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-01-01 11:00:29', 88, 71, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-25 06:30:41', 81, 66, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-01-22 14:18:35', 97, 12, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-07-14 00:33:36', 98, 55, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-13 19:00:59', 73, 51, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-09 15:44:08', 10, 72, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-05-06 16:21:41', 19, 62, 'DECLINED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-28 11:08:08', 75, 69, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-03-03 04:59:31', 76, 15, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-11-15 12:44:54', 9, 37, 'BLOCKED');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-09-19 22:56:35', 42, 1, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-04-23 00:41:35', 71, 33, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-08-17 10:52:55', 35, 41, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-01-02 23:22:44', 56, 85, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-04-03 22:59:33', 56, 98, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-07 18:32:55', 66, 93, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-11-01 00:32:05', 77, 91, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-11 09:40:07', 22, 21, 'FRIEND');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2023-02-09 19:01:26', 32, 66, 'REQUEST');
insert into friendships (sent_time, dst_person_id, src_person_id, status_name) values ('2022-10-11 02:24:11', 4, 16, 'BLOCKED');

insert into countries (name, full_name, internationalname, code2) values ('United States', 'Clari Stilliard', 'in quam', 'lnc708');
insert into countries (name, full_name, internationalname, code2) values ('Bulgaria', 'Vince Samett', 'turpis sed ante', 'eyt004');
insert into countries (name, full_name, internationalname, code2) values ('China', 'Abbi Pallant', 'lobortis convallis', 'mff574');
insert into countries (name, full_name, internationalname, code2) values ('Vietnam', 'Conney Yakhin', 'nulla', 'jie242');
insert into countries (name, full_name, internationalname, code2) values ('Czech Republic', 'Maddy Joselovitch', 'sapien non', 'xrn576');
insert into countries (name, full_name, internationalname, code2) values ('Poland', 'Al Clapson', 'volutpat', 'bjb448');
insert into countries (name, full_name, internationalname, code2) values ('Canada', 'Cherri Endle', 'et ultrices posuere', 'uxz434');
insert into countries (name, full_name, internationalname, code2) values ('Ukraine', 'Jessie Seaborne', 'dui luctus rutrum', 'waw167');
insert into countries (name, full_name, internationalname, code2) values ('Tanzania', 'Allyce Thonason', 'nulla pede ullamcorper', 'acf568');
insert into countries (name, full_name, internationalname, code2) values ('Indonesia', 'Leroi Brodest', 'venenatis', 'nse472');
insert into countries (name, full_name, internationalname, code2) values ('Nigeria', 'Pinchas Trewman', 'sed vestibulum sit', 'bdf089');
insert into countries (name, full_name, internationalname, code2) values ('Japan', 'Emogene Robey', 'a', 'lid173');
insert into countries (name, full_name, internationalname, code2) values ('Costa Rica', 'Delphine Swinn', 'est', 'ptd094');
insert into countries (name, full_name, internationalname, code2) values ('Russia', 'Morgen Von Der Empten', 'enim', 'bxx451');
insert into countries (name, full_name, internationalname, code2) values ('Philippines', 'Dag Willan', 'lobortis', 'mxg866');
insert into countries (name, full_name, internationalname, code2) values ('Yemen', 'Clarke Bank', 'nulla ac', 'xzv644');
insert into countries (name, full_name, internationalname, code2) values ('Ecuador', 'Munmro Calveley', 'eget semper', 'rpj497');
insert into countries (name, full_name, internationalname, code2) values ('Chile', 'Claudio Dawdry', 'nec molestie sed', 'hbh583');
insert into countries (name, full_name, internationalname, code2) values ('Finland', 'Ramon Jonson', 'vestibulum ac', 'srg858');
insert into countries (name, full_name, internationalname, code2) values ('Togo', 'Ailbert Wetherhead', 'consequat', 'tdn179');
insert into countries (name, full_name, internationalname, code2) values ('Madagascar', 'Brit Chretien', 'mi sit amet', 'lvm588');
insert into countries (name, full_name, internationalname, code2) values ('Uzbekistan', 'Bealle Gadie', 'turpis enim blandit', 'cjv455');
insert into countries (name, full_name, internationalname, code2) values ('Thailand', 'Kirk Manville', 'justo in', 'deb916');
insert into countries (name, full_name, internationalname, code2) values ('Panama', 'Caroline Laetham', 'vestibulum eget vulputate', 'abt059');
insert into countries (name, full_name, internationalname, code2) values ('Macedonia', 'Lauren Greensitt', 'eget congue eget', 'pbo503');
insert into countries (name, full_name, internationalname, code2) values ('Qatar', 'Archibald Blues', 'potenti in eleifend', 'uki949');
insert into countries (name, full_name, internationalname, code2) values ('Egypt', 'Sheilah Dowglass', 'potenti nullam', 'fye519');
insert into countries (name, full_name, internationalname, code2) values ('Colombia', 'Fey Dyshart', 'dapibus', 'hna601');
insert into countries (name, full_name, internationalname, code2) values ('Belarus', 'Janie Macci', 'sed interdum', 'wqe637');
insert into countries (name, full_name, internationalname, code2) values ('Bosnia and Herzegovina', 'Gaelan Labuschagne', 'adipiscing molestie hendrerit', 'jpi380');
insert into countries (name, full_name, internationalname, code2) values ('Peru', 'Cate Tuttle', 'maecenas ut', 'llk852');
insert into countries (name, full_name, internationalname, code2) values ('Ivory Coast', 'Janaya Shoutt', 'nonummy', 'xuf584');
insert into countries (name, full_name, internationalname, code2) values ('Mexico', 'Aldis Salasar', 'pretium iaculis', 'jvp224');
insert into countries (name, full_name, internationalname, code2) values ('Bangladesh', 'Emalia Corain', 'vestibulum', 'zhl774');
insert into countries (name, full_name, internationalname, code2) values ('Sweden', 'Antonetta Choat', 'accumsan', 'heb819');
insert into countries (name, full_name, internationalname, code2) values ('Pakistan', 'Dasya Chern', 'sapien', 'luv312');
insert into countries (name, full_name, internationalname, code2) values ('Paraguay', 'Anthony Painswick', 'pulvinar nulla pede', 'tro395');
insert into countries (name, full_name, internationalname, code2) values ('Mongolia', 'Breanne Esslemont', 'sed', 'uwe981');
insert into countries (name, full_name, internationalname, code2) values ('Armenia', 'Karine Claydon', 'blandit', 'toy004');
insert into countries (name, full_name, internationalname, code2) values ('France', 'Brynn Penswick', 'curabitur', 'odh498');

insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Vihti', 72, 22, 'Bultman', 'eu');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Glad', 79, 39, 'Bunting', 'rutrum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Valencia', 25, 38, 'West', 'morbi');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Sumusţā as Sulţānī', 53, 28, 'Oakridge', 'morbi');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kačanik', 35, 6, 'Garrison', 'sociis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Lashma', 81, 35, 'Meadow Valley', 'congue');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Weiyanggong', 95, 34, 'Sunfield', 'nisl');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Lom Sak', 7, 6, 'Mesta', 'turpis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Zumarraga', 20, 9, 'Anzinger', 'aenean');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Akashi', 28, 5, 'Springs', 'consequat');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Huanshan', 25, 34, 'Carioca', 'vestibulum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Aricagua', 65, 28, '4th', 'aliquet');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Depok', 9, 6, 'Parkside', 'elit');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Sarykemer', 33, 33, 'Maple', 'eros');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Cachoeirinha', 83, 5, 'Pawling', 'magnis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Detupia', 3, 31, 'Chinook', 'tristique');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Moravská Nová Ves', 1, 30, 'Browning', 'potenti');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Revolucion Verde', 3, 29, 'Nova', 'consequat');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Altan-Ovoo', 2, 28, 'Anhalt', 'at');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Ghouazi', 69, 27, 'Amoth', 'pede');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Pirca', 98, 26, 'Cardinal', 'convallis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Mantalongon', 12, 25, 'Barby', 'etiam');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Oefatu', 66, 24, 'Rockefeller', 'blandit');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nancy', 41, 23, 'Cardinal', 'id');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Zhongdong', 100, 22, 'Acker', 'dignissim');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Fonte Boa', 27, 21, 'Maywood', 'id');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Gvardeysk', 94, 20, 'John Wall', 'bibendum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Farafenni', 92, 19, 'Miller', 'morbi');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Velagići', 61, 18, 'Burrows', 'justo');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nechanice', 12, 17, 'Jenna', 'scelerisque');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Zhaowanzhuang', 39, 16, 'Dryden', 'nulla');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Longwu', 57, 32, 'Farragut', 'suspendisse');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Verkhnevilyuysk', 90, 15, 'Hallows', 'habitasse');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Polo', 31, 5, 'Southridge', 'non');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kefar Yona', 17, 8, 'Clove', 'mattis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Zhigulevsk', 6, 14, 'Katie', 'nulla');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Amānzī', 85, 13, 'Hallows', 'quis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Niono', 40, 12, 'Manitowish', 'aliquam');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Xiangfu', 75, 11, 'Hanson', 'sollicitudin');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nay Pyi Taw', 69, 10, 'Brentwood', 'nulla');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kebonbencoy', 73, 34, 'Mandrake', 'posuere');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nangkasari', 80, 36, 'Onsgard', 'dictumst');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Trois-Rivières', 16, 9, 'Waubesa', 'felis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Batasan Bata', 78, 31, 'Loftsgordon', 'fermentum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Frederiksberg', 45, 26, 'Vera', 'ipsum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Chang’an', 5, 8, 'Summit', 'aliquet');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Cikabuyutan Barat', 20, 7, 'Jay', 'ac');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Río Alejandro', 96, 6, 'Fieldstone', 'vel');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Sidi Moussa', 90, 5, 'Garrison', 'vitae');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Serednye Vodyane', 59, 2, 'Anniversary', 'ligula');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Naru', 30, 1, 'Steensland', 'porttitor');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Banjar Sedang', 47, 2, 'Sommers', 'massa');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Aricapampa', 44, 3, 'Bashford', 'odio');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Perpignan', 100, 4, 'Summer Ridge', 'consequat');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Soavinandriana', 57, 39, 'Nelson', 'augue');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('João Pessoa', 23, 12, 'Tennyson', 'venenatis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Shchëkino', 75, 4, 'New Castle', 'faucibus');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Burgastai', 52, 5, 'Superior', 'justo');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Ruyigi', 40, 6, 'Pawling', 'eget');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Daxing', 45, 10, 'Helena', 'cubilia');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Wiset Chaichan', 67, 11, 'Texas', 'nulla');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kondinskoye', 26, 12, 'Prentice', 'libero');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Castainço', 39, 16, 'Di Loreto', 'nullam');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Magapit', 45, 13, 'Bowman', 'tortor');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Tilburg', 59, 14, 'Division', 'mi');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Gazli', 28, 23, 'Esker', 'magna');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Irará', 31, 15, 'Raven', 'nullam');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Chiguirip', 92, 16, 'Springview', 'consectetuer');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Tlatah', 66, 37, 'Loomis', 'mi');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Colonia Yguazú', 31, 17, 'Crescent Oaks', 'lacus');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kalianda', 66, 18, 'Vidon', 'parturient');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Būr Safājah', 42, 19, 'Dryden', 'tempus');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kalmar', 67, 20, 'Eliot', 'quam');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Phủ Thông', 87, 1, 'Forest', 'nunc');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Jianyi', 63, 34, 'Veith', 'libero');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Fresno', 86, 12, 'Pine View', 'orci');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Pokrovka', 43, 27, 'Vidon', 'fusce');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nsukka', 71, 26, 'American', 'at');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Bang Phae', 77, 22, 'Anniversary', 'nunc');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Lijia', 83, 23, 'Chinook', 'ipsum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Duishan', 43, 11, 'Springs', 'venenatis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Claye-Souilly', 93, 24, 'Wayridge', 'non');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Linmansangan', 97, 36, 'Sage', 'curae');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Ambatolampy', 81, 24, 'Moulton', 'varius');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Couço', 6, 39, 'Bowman', 'sit');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Kaminoyama', 97, 25, 'Buena Vista', 'nunc');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Banquero', 81, 26, 'Division', 'suspendisse');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Stockholm', 33, 23, 'Crest Line', 'in');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Zhenziliang', 100, 27, 'Manitowish', 'id');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Luowan', 63, 28, 'Dunning', 'est');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Moryń', 23, 29, 'Lindbergh', 'quis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Novyye Cherëmushki', 18, 31, 'Bultman', 'iaculis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Desa Borogojol', 78, 32, 'Waxwing', 'integer');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Dalkey', 100, 1, 'Myrtle', 'rhoncus');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Tongyang', 15, 33, 'Mosinee', 'vestibulum');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('San Antonio del Monte', 69, 15, '5th', 'sapien');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Piritiba', 1, 34, 'Blackbird', 'sed');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Nobres', 97, 35, 'Kedzie', 'hac');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Parzęczew', 31, 27, 'Debs', 'magnis');
insert into cities (name, gismeteo_id, country_id, district, sub_district) values ('Chabany', 98, 36, 'Myrtle', 'cum');
