DROP TABLE IF EXISTS public.countries;

CREATE TABLE IF NOT EXISTS public.countries
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255),
    full_name character varying(255),
    code2 character varying(2),
    international_name character varying(255),
    CONSTRAINT countries_key PRIMARY KEY (id)
)