drop table if exists storage;

create table if not exists storage (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    owner_Id bigint not null,
	file_Name text not null,
    file_Size bigint not null,
    file_Type varchar(25) not null,
    created_At timestamp without time zone not null
)
