DROP TABLE IF EXISTS Weather;

CREATE TABLE IF NOT EXISTS Weather
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    open_weather_id bigint,
    city character varying(255),
    clouds character varying(150),
    date timestamp without time zone,
    temp real,
    CONSTRAINT weather_key PRIMARY KEY (id)
);